NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
MV_SCC <- SCC[grep("vehicle", SCC$Short.Name, ignore.case = TRUE), ]
SCC_MVlist <- unique(MV_SCC$SCC)
NEI_Baltimore <- subset(NEI, fips == "24510")
NEI_California <- subset(NEI, fips == "06037")
MVNEI_Baltimore <- subset(NEI_Baltimore, SCC %in% SCC_MVlist)
totalPM_MV <- with(MVNEI_Baltimore, tapply(Emissions, year, sum, na.rm=TRUE))
MVNEI_California <- subset(NEI_California, SCC %in% SCC_MVlist)
totalPM_MV_Cal <- with(MVNEI_California, tapply(Emissions, year, sum, na.rm=TRUE))
png("plot6.png")
par(mfrow = c(1,2))
barplot(totalPM_MV, xlab = "year", ylab = "Baltimore")
barplot(totalPM_MV_Cal, xlab = "year", ylab = "California")
mtext("Total PM2.5 Emissions from motor vehicles yearwise", side = 3, line = -2, outer = TRUE)
dev.off()